### ISSUE TITLE
API: UserStats model

### ISSUE THREAD

**Issue by hafager** [paradise-fantasy/fantasy#159]
```javascript
{
  user: String,
  gameDay: Number,
  score: Number,
  rank: Number
}
```

Should exist one for each day for each user.

**Comment by tormiss** [comment]
# How to help

**New Branches**
To enable a smooth merge, all attempts to help resolve this issue should be pulled from branch ```userstats-model#159``` where the model is already implemented.

**Merge Requests**
Merge Requests should be done towards ```userstats-model#159```, so that a single feature-merge can be done with master at a later time

# Tasks
Here is a list of identified remaining tasks in this issue
## API
- [x] Implement ```getUserTotalScore``` using model in /me/stats
- [x] Implement ```getUserWeekScore``` using model in /me/stats
- [x] Implement ```getUserRankDiff``` using model in /me/stats
- [x] Implement ```getUserScoreDiff``` using model in /me/stats
- [ ] Convert /me/stats ```getUserRank``` to use new model
- [ ] Convert /me/leagues ```get``` to use new model
- [ ] Convert /o/league ```get``` to use new model
- [ ] Convert /a/users ```get``` to use new model
## WEB
### Components
- [ ] Apply model to ```WeeklyScoreBadge``` 
- [ ] Apply model to ```TotalScoreBadge``` 
- [ ] Apply model to ```PlayerRankBadge``` 
### APP
- [ ] Apply model to Leagues
- [ ] Apply model to League

**Comment by tormiss** [comment]
After the last commit to branch ```userstats-model#159``` API end-point /me/stats now returns data like this:
```
{
  "userCount": 13219,
  "globalRank": 4,
  "totalScore": 10,
  "weekScore": 10,
  "globalRankDiff": 0,
  "scoreDiff": 0
}
```

**Comment by tormiss** [comment]
After the last commit to branch ```userstats-model#159``` API end-point /me/stats now returns data like this:
```
{
  "userCount": 13219,
  "globalRank": 4,
  "globalRankDiff": 0,
  "totalScore": 10,
  "totalScoreDiff": 0,
  "weekScore": 1,
  "weekScoreDiff": 0
}
```

**Comment by tormiss** [comment]
API end-point GET /o/league now looks like this:
```
{
  "_id": "58e224fd6251296380b1bd23",
  "name": "Privat Test Liga",
  "creator": "58a074b42b3b741320cb1d8f",
  "code": "r1BbSsypx",
  "users": [
    {
      "_id": "58a074b42b3b741320cb1d8f",
      "name": "domrot",
      "score": 24,
      "scoreDiff": 9
    },
    {
      "_id": "58c597467d14af001a2c748d",
      "name": "Hafager",
      "score": 12,
      "scoreDiff": 4
    }
  ],
  "__v": 0
}
```
